name: Use Reusable Docker Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: muna1991/Docker-build-demo/.github/workflows/hello-world.yml@main  # Use the reusable workflow here at the jobs level
    with:
      image_name: ${{ vars.IMAGE_NAME }}  # Use the environment variable
      tag: ${{ secrets.TAG }}  # Use the secret
    runs-on: self-hosted  # Specify
