name: Use Reusable Docker Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: muna1991/Docker-build-demo/.github/workflows/hello-world.yml@main  # Use the reusable workflow
    with:
      image_name: ${{ vars.IMAGE_NAME }}  # Pass the environment variable
      tag: ${{ vars.TAG }}              # Pass the secret as an input
              # Explicitly pass the secret to the reusable workflow
